TEMPLATEROOT = ..

# compilation flags for gdb

CFLAGS  = -O0 -g3
ASFLAGS = -g3

# object files

OBJS= tm_stm32f1_spi.o tm_stm32f1_fonts.o tm_stm32f1_ili9341.o main.o $(STARTUP) 
OBJS+= tm_stm32f1_gpio.o

# include common make file

include $(TEMPLATEROOT)/Makefile.common


