TEMPLATEROOT = ..

# compilation flags for gdb

CFLAGS  = -O0 -g3
ASFLAGS = -g3

# object files

OBJS= main.o SPI.o tm_stm32f1_ili9341.o tm_stm32f1_fonts.o stm32f1xx_hal_gpio.o stm32f1xx_hal_spi.o stm32f1xx_hal_dma.o stm32f1xx_hal_rcc.o stm32f1xx_hal_cortex.o stm32f1xx_hal.o xpt2046.o FatFs/diskio.o FatFs/ff.o FatFs/ff_gen_drv.o FatFs/sd_diskio.o FatFs/stm3210c_eval_sd.o $(STARTUP) 
# include common make file

include $(TEMPLATEROOT)/Makefile.common


